package Model;
// Generated 13-jul-2019 18:21:01 by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idlogin;
     private String username;
     private int pass;

    public Login() {
    }

    public Login(String username, int pass) {
       this.username = username;
       this.pass = pass;
    }
   
    public Integer getIdlogin() {
        return this.idlogin;
    }
    
    public void setIdlogin(Integer idlogin) {
        this.idlogin = idlogin;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public int getPass() {
        return this.pass;
    }
    
    public void setPass(int pass) {
        this.pass = pass;
    }




}


