package Model;
// Generated 14-jul-2019 8:04:24 by Hibernate Tools 4.3.1



/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String telefono;

    public Registro() {
    }

    public Registro(String nombre, String telefono) {
       this.nombre = nombre;
       this.telefono = telefono;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


